services:
  cups:
    image: ghcr.io/akiba-hs/cups
    build: .
    restart: always
    privileged: true
    ports:
      - "631:631"
    volumes:
      - "./config:/etc/cups"
      - "/dev/bus/usb:/dev/bus/usb"
      - "/run/udev:/run/udev:ro"
    environment:
      - TZ=Asia/Tomsk
      - CUPSADMIN=akiba
      - CUPSPASSWORD=akiba1337
